### ISSUE TITLE
Can install

### ISSUE THREAD

**Issue by tb59427** [kedder/openvario-shell#139]
Hi,

running the install script on an internet connected OV returns numerous download errors when running opkg update. All of them reference a download from ftp.openvario.org/feed-kirkstone/openvario_57_lvds/Packages.gz and from ///usb-stick

Could you please look into this?

cheers
Torsten

**Comment by tb59427** [comment]
Most current build (built yesterday) on a Stefly 5.7"

Gruß
-tb
Am 2. Juni 2022, 09:44 +0200 schrieb Andrey Lebedev ***@***.***>:

**Comment by kedder** [comment]
Yeah, currently ovshell is not really installable on top of vanilla image, because it was never released. However, one can build your own with ovshell pre-installed using my [PPA](https://github.com/kedder/openvario-ppa).

I've built the latest version for 5.7" with ovshell for you: grab it from here: https://www.dropbox.com/s/wdlkpjv9ge24bd8/OpenVario-linux-openvario-image-ovshell-glibc-ipk-22153-openvario-57-lvds.rootfs.img.gz?dl=0
